### ISSUE TITLE
Biodiversity integration

### ISSUE THREAD

**Issue by MikePetersNZ** [Datalinker-Org/Geospatial#22]
Years ago I built a national biodiversity management system for conservation groups called pipi4.  I am now building an open-source cloud project for managing areas of biodiversity on-farm (eg a QEII block). Covering pests, planting, running a nursery, fencing, monitoring etc. It would be great to integrate via Open API with other systems. 

Is anyone interested in biodiversity on-farm?

**Comment by MikePetersNZ** [comment]
Some thoughts on areas of biodiversity on-farm. 

They can exist within paddocks, across multiple paddocks and across farm boundaries. They need to have their own spatial definition that is not nested within the "holdings, sites and plots" entity diagram. A farmer should be able to draw a biodiversity polygon on their farm holding anywhere. The same applies off-farm. I once built a national system for conservation groups and private landowners called pipi4. This was the only definition that worked in practice.

This would enable maximum utility by those on and off-farm.

**Comment by cookeac** [comment]
I've been thinking about possible solutions to monitoring biodiversity. Here is a suggestion that I would like to discuss at a coming meeting:

1. Define a categorisation for land covers that supports common NZ land covers. This has pretty much already been done with the LCDB (Land Cover Database) classification v5. See https://lris.scinfo.org.nz/document/22491-lcdb-classes-at-version5/
This just needs to work on a farm scale as well as the catchment and larger size of the current LCDB polygons.
If we were using the scheme+id mechanism we have used elsewhere, you could use **"nz.lcdb.5"** as the scheme and the actual classification as the value/id.

2. Because landcover and whether an area is a wetland are not mutually exclusive, LCDB also has an "is wetland" flag for any polygon, with a "yes"/"no" value. We could do the same (for instance **"nz.lcdb.5.wetland", "yes/no"**), though I also like the idea of a wetland potentially being a polygon type. 

3. Issue #25 proposes that the `classification` array property be moved from its current location in `PlotResource` to a `LandUseResource` and that PlotResource is therefore just one type of LandUseResource. We could make a `LandCoverResource` that was a polygon (or polyline for shelterbelts?) that also derived from LandUseResource and therefore could be classified with these classifications.

4. In the EU, biodiversity polygons are also used to monitor species distribution. From what I can see this uses a classification based on species name. I'm trying to find out if there are any metrics (e.g. density) or whether they are just indications that a species (e.g. a type of bird, bat, or plant) has been observed in that area. We could potentially add a `speciesDistribution` array to a LandCoverResource.

**Comment by cookeac** [comment]
Adding a link to [T G O'Brien's paper](https://www.jfernandezv.com/_files/ugd/9b9dde_b573d7fe7c1a474c91156ec341557a3d.pdf#page=86) on abundance, density, and relative abundance metrics in population measures, in case we feel that any of this is helpful for considering species measures.

**Comment by MikePetersNZ** [comment]
iNaturalist is very popular in NZ for biodiversity observations. A kind of citizen crowdsourcing of observational data. iNaturalist has a great API for integration. Observations are points with 1 or more photos attached. Polygon project areas can be defined and observations included in them. Our place is now defined as a Project Area and this follows the Parcel boundary by choice. so all my observations are linked to this project area.

https://inaturalist.nz/projects/mt-chocolate

SHMAK used for catchment water quality monitoring by farmer-led catchment groups is another system.

QE2 reps often visit private landowners to do a condition survey and provide helpful advice. This is often a list of pests, weeds, threats, etc which seem from memory to be attached to the QE2 covenant polygon.

So will biodiversity observations be attached to a point, line, and/or polygon? How will this work for 2-way integration without changing the spatial context?

**Comment by cookeac** [comment]
Notes from today's meeting (27/4/2022)
- Let's pick up on Observations (as opposed to attributes of a land area) in a future meeting. Mike's comments above absolutely apply.
- We looked at the [FAO scheme for land covers](https://www.fao.org/3/i5232e/i5232e.pdf) (and EU and ISO seem to be adopting this scheme too). It is complex, but we don't need to reproduce the scheme; we just need to address it with something similar to `ClassificationType`, so you can specify the scheme that you are using and the appropriate level of detail.
- We probably need some array or similar mechanism to identify the species managed or observed. For instance, does this area contain Kauri (Agathus australis)? What about Phytophthora agathidicida (Kauri dieback disease)? These are sort of analogous to our CropType, but we might want to know a summary from the density observations, and whether the species is protected, incidental, or a pest.

Proposing that:
- `LandCoverResource` should extend `LandUseResource` (see the diagram)
- Add a `coverClassification` array
- Add a `containsSpecies` array

Other suggestions welcome!

**Comment by cookeac** [comment]
What might a `SpeciesType` look like when talking about the `containedSpecies` for a polygon? (Potentially the same structure could be used for an observation at a point or on a transect line). How about this:
| Attribute | Type | Description |
| --- | --- | --- |
| name | string | Human readable common name (e.g. Kauri) |
| taxonomicName | string | Definitive taxonomic name (e.g. Agathis australis) |
| classification | [ClassificationType](https://github.com/Datalinker-Org/Geospatial/blob/master/types/ClassificationType.json) | A scheme-based classification, so you can differentiate native species, introduced, pathogen, pest, etc. |
| abundance | enumeration | DAFOR scale [abundance categorisation](https://en.wikipedia.org/wiki/Abundance_(ecology)#Measurement) |

DAFOR enumeration values for abundance: Dominant, Abundant, Frequent, Occasional, Rare.
From: [Morris, Peter (1995)](https://doi.org/10.4324/9780203892909). Methods of Environmental Assessment. University College

A **classification** example for New Zealand could be derived from the preliminary Biodiversity Principles for New Zealand's Agriculture ([McLeod et al, 2021](https://doi.org/10.1002/pan3.10285)) by using the biodiversity groups and adding pests and pathogens from the management categories in that paper.
